/*CRIANDO BANCO DE DADOS*/
CREATE DATABASE SUCOS;
CREATE DATABASE SUCOS2;

/*APAGANDO BANCO DE DADOS*/
DROP DATABASE SUCOS2;

/*SELECIONA O BANCO DE DADOS*/
USE SUCOS;

/*CRIANDO TABELA CLIENTE*/
USE SUCOS;
CREATE TABLE tb_cliente
(CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO VARCHAR(50),
ENDERECO2 VARCHAR(50),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(50),
CEP VARCHAR(8),
IDADE SMALLINT,
GENERO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA BIT(1));

/*CRIANDO TABELA VENDEDORES*/
USE SUCOS;
CREATE TABLE tb_vendedores
(MATRICULA VARCHAR(5),
NOME VARCHAR(100),
PERCENTUAL_COMISSAO FLOAT,
DATA_ADMISSAO DATE,
DE_FERIAS BIT);

/*CRIANDO TABELA PRODUTOS*/
USE SUCOS;
CREATE TABLE `sucos`.`tb_produto` (
  `PRODUTO` VARCHAR(20) NULL,
  `NOME` VARCHAR(150) NULL,
  `EMBALAGEM` VARCHAR(50) NULL,
  `TAMANHO` VARCHAR(50) NULL,
  `SABOR` VARCHAR(50) NULL,
  `PRECO_LISTA` FLOAT NULL);
  
  /*ADICIONANDO DADOS A TABELA PRODUTO*/
  USE SUCOS;  
  INSERT INTO tb_produto(PRODUTO, NOME,  EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
  VALUES('1040107', 'Light - 350 ml - Melância', 'Lata', '350 ml', 'Melância', 4.56);  
  INSERT INTO tb_produto(PRODUTO, NOME,  EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
  VALUES('10037797', 'Clean - 2 litros - Laranja', 'PET', '2 litros', 'Laranja', 16.01);  
  INSERT INTO tb_produto(PRODUTO, NOME,  EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
  VALUES('1000889', 'Sabor da Montanha - 700 ml - Uva', 'Garrafa', '700 ml', 'Uva', 6.31);  
  INSERT INTO tb_produto(PRODUTO, NOME,  EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
  VALUES('1004327', 'Videira do Campo - 700 ml - Melância', 'PET', '700 ml', 'Melância', 19.51);  
  INSERT INTO tb_produto(PRODUTO, NOME,  EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
  VALUES('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml', 'Limão', 3.20);  
  INSERT INTO tb_produto(PRODUTO, NOME,  EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
  VALUES('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml', 'Manga', 5.18);  
  SELECT * FROM tb_produto;
  
   /*ADICIONANDO DADOS A TABELA VENDEDORES*/
  USE SUCOS;    
  INSERT INTO tb_vendedores(MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
  VALUES('00235','Márcio Almeida Silva',  0.08, '2014-08-15', 0);  
  INSERT INTO tb_vendedores(MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
  VALUES('00236','Cláudia Morais',  0.08, '2013-09-17', 1);  
  INSERT INTO tb_vendedores(MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
  VALUES('00237','Roberta Martins',  0.11, '2017-03-18', 1);  
  INSERT INTO tb_vendedores(MATRICULA, NOME, PERCENTUAL_COMISSAO, DATA_ADMISSAO, DE_FERIAS)
  VALUES('00238','Péricles Alves',  0.11, '2016-08-21', 0); 
  SELECT * FROM tb_vendedores;
  
  /*ALTERANDO DADOS DA TABELA PRODUTO*/
  USE SUCOS;
  UPDATE tb_produto SET EMBALAGEM  = 'Lata', PRECO_LISTA = 2.46
  WHERE PRODUTO = '544931';
  UPDATE tb_produto SET EMBALAGEM  = 'Garrafa'
  WHERE PRODUTO = '1078680';
  SELECT * FROM tb_produto;
  
   /*ALTERANDO DADOS DA TABELA VENDEDORES*/
  USE SUCOS;
  UPDATE tb_vendedores SET PERCENTUAL_COMISSAO  = 0.11 WHERE MATRICULA = '00236';  
  UPDATE tb_vendedores SET NOME  = 'José Geraldo da Fonseca Junior' WHERE MATRICULA = '00233'; 
  SELECT * FROM tb_vendedores;
  
  /*APAGANDO DADOS DA TABELA PRODUTO*/
  DELETE FROM tb_produto WHERE PRODUTO = '1078680';
  SELECT * FROM tb_produto;
  
  /*APAGANDO DADOS DA TABELA VENDERORES*/
  DELETE FROM tb_vendedores WHERE MATRICULA = '00233';
  SELECT * FROM tb_vendedores;
  
  /*ADICIONANDO CHAVE PRIMARIA NA TABELA PRODUTO*/
  USE SUCOS;
  ALTER TABLE tb_produto ADD PRIMARY KEY (PRODUTO);
  SELECT * FROM tb_produto;  
  
  /*ADICIONANDO CAMPO PRIMARY KEY E DATA DE NASCIMENTO NA TABELA CLIENTE*/
  USE SUCOS;
  ALTER TABLE tb_cliente ADD PRIMARY KEY(CPF);
  ALTER TABLE tb_cliente ADD COLUMN(DATA_NASCIMENTO DATE);
  SELECT * FROM tb_cliente;
  
  INSERT INTO tb_cliente(CPF, NOME, ENDERECO, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, GENERO, LIMITE_CREDITO, VOLUME_COMPRA,
  PRIMEIRA_COMPRA, DATA_NASCIMENTO)
  VALUES('00022233365', 'João Nascimento Gonçalves', 'Rua Zero 01', 'Rua Zero 02', 'Parque Florestal', 'São Bernado do Campo', 'São Paulo',
  '00056055', 30, 'M', 12500.00, 1000.00, 0, '1989-05-26');
  SELECT * FROM tb_cliente;
  
  /*ADICIONANDO CHAVE PRIMARIA NA TABELA VENDEDORES*/
  USE SUCOS;  
  ALTER TABLE tb_vendedores ADD PRIMARY KEY (MATRICULA);
  SELECT * FROM tb_vendedores; 
      
      
  /*REFORMULANDO PROJETO*/

  USE sucos;

  DROP TABLE tb_cliente;

  DROP TABLE tb_produto;

  CREATE TABLE tb_cliente
  ( CPF VARCHAR (11) ,
  NOME VARCHAR (100) ,
  ENDERECO1 VARCHAR (150) ,
  ENDERECO2 VARCHAR (150) ,
  BAIRRO VARCHAR (50) ,
  CIDADE VARCHAR (50) ,
  ESTADO VARCHAR (2) ,
  CEP VARCHAR (8) ,
  DATA_NASCIMENTO DATE,
  IDADE SMALLINT,
  SEXO VARCHAR (1) ,
  LIMITE_CREDITO FLOAT ,
  VOLUME_COMPRA FLOAT ,
  PRIMEIRA_COMPRA BIT );

  ALTER TABLE tb_cliente ADD PRIMARY KEY (CPF);

  CREATE TABLE tb_produto
  (PRODUTO VARCHAR (20) ,
  NOME VARCHAR (150) ,
  EMBALAGEM VARCHAR (50) ,
  TAMANHO VARCHAR (50) ,
  SABOR VARCHAR (50) ,
  PRECO_LISTA FLOAT);

  ALTER TABLE tb_produto ADD PRIMARY KEY (PRODUTO);

  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('19290992743','Fernando Cavalcante','R. Dois de Fevereiro','','Água Santa','Rio de Janeiro','RJ','22000000','2000-02-12',18,'M',100000,200000,1);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('2600586709','César Teixeira','Rua Conde de Bonfim','','Tijuca','Rio de Janeiro','RJ','22020001','2000-03-12',18,'M',120000,220000,0);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('95939180787','Fábio Carvalho','R. dos Jacarandás da Península','','Barra da Tijuca','Rio de Janeiro','RJ','22002020','1992-01-05',16,'M',90000,180000,1);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('9283760794','Edson Meilelles','R. Pinto de Azevedo','','Cidade Nova','Rio de Janeiro','RJ','22002002','1995-10-07',22,'M',150000,250000,1);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('7771579779','Marcelo Mattos','R. Eduardo Luís Lopes','','Brás','São Paulo','SP','88202912','1992-03-25',25,'M',120000,200000,1);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('5576228758','Petra Oliveira','R. Benício de Abreu','','Lapa','São Paulo','SP','88192029','1995-11-14',22,'F',70000,160000,1);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('8502682733','Valdeci da Silva','R. Srg. Édison de Oliveira','','Jardins','São Paulo','SP','82122020','1995-10-07',22,'M',110000,190000,0);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('1471156710','Érica Carvalho','R. Iriquitia','','Jardins','São Paulo','SP','80012212','1990-09-01',27,'F',170000,245000,0);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('3623344710','Marcos Nougeuira','Av. Pastor Martin Luther King Junior','','Inhauma','Rio de Janeiro','RJ','22002012','1995-01-13',23,'M',110000,220000,1);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('50534475787','Abel Silva ','Rua Humaitá','','Humaitá','Rio de Janeiro','RJ','22000212','1995-09-11',22,'M',170000,260000,0);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('5840119709','Gabriel Araujo','R. Manuel de Oliveira','','Santo Amaro','São Paulo','SP','80010221','1985-03-16',32,'M',140000,210000,1);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('94387575700','Walber Lontra','R. Cel. Almeida','','Piedade','Rio de Janeiro','RJ','22000201','1989-06-20',28,'M',60000,120000,1);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('8719655770','Carlos Eduardo','Av. Gen. Guedes da Fontoura','','Jardins','São Paulo','SP','81192002','1983-12-20',34,'M',200000,240000,0);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('5648641702','Paulo César Mattos','Rua Hélio Beltrão','','Tijuca','Rio de Janeiro','RJ','21002020','1991-08-30',26,'M',120000,220000,0);
  INSERT INTO tb_cliente (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('492472718','Eduardo Jorge','R. Volta Grande','','Tijuca','Rio de Janeiro','RJ','22012002','1994-07-19',23,'M',75000,95000,1);

  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1040107','Light - 350 ml - Melância','Lata','350 ml','Melância',4.555);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.008);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva',6.309);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1004327','Videira do Campo - 1,5 Litros - Melância','PET','1,5 Litros','Melância',19.51);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1088126','Linha Citros - 1 Litro - Limão','PET','1 Litro','Limão',7.004);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('544931','Frescor do Verão - 350 ml - Limão','Lata','350 ml','Limão',2.4595);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1078680','Frescor do Verão - 470 ml - Manga','Garrafa','470 ml','Manga',5.1795);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1042712','Linha Citros - 700 ml - Limão','Garrafa','700 ml','Limão',4.904);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('788975','Pedaços de Frutas - 1,5 Litros - Maça','PET','1,5 Litros','Maça',18.011);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1002767','Videira do Campo - 700 ml - Cereja/Maça','Garrafa','700 ml','Cereja/Maça',8.41);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('231776','Festival de Sabores - 700 ml - Açai','Garrafa','700 ml','Açai',13.312);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('479745','Clean - 470 ml - Laranja','Garrafa','470 ml','Laranja',3.768);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1051518','Frescor do Verão - 470 ml - Limão','Garrafa','470 ml','Limão',3.2995);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1101035','Linha Refrescante - 1 Litro - Morango/Limão','PET','1 Litro','Morango/Limão',9.0105);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('229900','Pedaços de Frutas - 350 ml - Maça','Lata','350 ml','Maça',4.211);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1086543','Linha Refrescante - 1 Litro - Manga','PET','1 Litro','Manga',11.0105);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('695594','Festival de Sabores - 1,5 Litros - Açai','PET','1,5 Litros','Açai',28.512);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('838819','Clean - 1,5 Litros - Laranja','PET','1,5 Litros','Laranja',12.008);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('326779','Linha Refrescante - 1,5 Litros - Manga','PET','1,5 Litros','Manga',16.5105);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('520380','Pedaços de Frutas - 1 Litro - Maça','PET','1 Litro','Maça',12.011);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1041119','Linha Citros - 700 ml - Lima/Limão','Garrafa','700 ml','Lima/Limão',4.904);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('243083','Festival de Sabores - 1,5 Litros - Maracujá','PET','1,5 Litros','Maracujá',10.512);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('394479','Sabor da Montanha - 700 ml - Cereja','Garrafa','700 ml','Cereja',8.409);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('746596','Light - 1,5 Litros - Melância','PET','1,5 Litros','Melância',19.505);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('773912','Clean - 1 Litro - Laranja','PET','1 Litro','Laranja',8.008);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('826490','Linha Refrescante - 700 ml - Morango/Limão','Garrafa','700 ml','Morango/Limão',6.3105);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('723457','Festival de Sabores - 700 ml - Maracujá','Garrafa','700 ml','Maracujá',4.912);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('812829','Clean - 350 ml - Laranja','Lata','350 ml','Laranja',2.808);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('290478','Videira do Campo - 350 ml - Melância','Lata','350 ml','Melância',4.56);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('783663','Sabor da Montanha - 700 ml - Morango','Garrafa','700 ml','Morango',7.709);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('235653','Frescor do Verão - 350 ml - Manga','Lata','350 ml','Manga',3.8595);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1002334','Linha Citros - 1 Litro - Lima/Limão','PET','1 Litro','Lima/Limão',7.004);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1013793','Videira do Campo - 2 Litros - Cereja/Maça','PET','2 Litros','Cereja/Maça',24.01);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1096818','Linha Refrescante - 700 ml - Manga','Garrafa','700 ml','Manga',7.7105);
  INSERT INTO tb_produto (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1022450','Festival de Sabores - 2 Litros - Açai','PET','2 Litros','Açai',38.012);

  /*CRIANDO CONSULTAS*/
  SELECT * FROM tb_cliente;

  SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP,
  DATA_NASCIMENTO, IDADE, SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA
  FROM tbcliente;

  SELECT CPF, NOME FROM tb_cliente;
  SELECT CPF, NOME FROM tb_cliente LIMIT 5;
  SELECT CPF AS CPF_CLIENTE, NOME AS NOME_CLIENTE FROM tb_cliente;
  SELECT NOME, CPF, SEXO, IDADE, DATA_NASCIMENTO FROM tb_cliente;
 
  /*SELECIONANDO NOME E MATRICULA DO VENDEDORES*/
  SELECT NOME, MATRICULA FROM tb_vendedores;
  
  /*CRIANDO CONSULTAS COM FILTROS*/  
  SELECT * FROM tb_produto WHERE PRODUTO = '544931';  
  SELECT * FROM tb_cliente WHERE CIDADE = 'Rio de Janeiro';  
  SELECT * FROM tb_produto WHERE SABOR = 'Cítricos';  
  UPDATE tb_produto SET SABOR = 'Cítricos' WHERE SABOR = 'Limão'; #Alterando os valores 
  SELECT * FROM tb_vendedores WHERE NOME = 'Claudia Morais';
  
  SELECT * FROM tb_cliente;
  SELECT * FROM tb_cliente WHERE IDADE = 22;
  SELECT * FROM tb_cliente WHERE IDADE > 22;
  SELECT * FROM tb_cliente WHERE IDADE < 22;
  SELECT * FROM tb_cliente WHERE IDADE >= 22;
  SELECT * FROM tb_cliente WHERE IDADE <= 22;
  SELECT * FROM tb_cliente WHERE IDADE <> 22;
  
  SELECT * FROM tb_produto WHERE PRECO_LISTA = 16.008;  
  SELECT * FROM tb_produto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009; #CONSULTA ENTRE VALORES
  
  /*VERIFICANDO VENDEDORES QUE POSSUEM COMISSÃO MAIOR QUE 10% */
  SELECT NOME, PERCENTUAL_COMISSAO FROM tb_vendedores WHERE PERCENTUAL_COMISSAO > 0.10;
  
  SELECT * FROM tb_cliente;  
  SELECT * FROM tb_cliente WHERE DATA_NASCIMENTO = '1995-01-13';  
  SELECT * FROM tb_cliente WHERE DATA_NASCIMENTO > '1995-01-13';
  SELECT * FROM tb_cliente WHERE DATA_NASCIMENTO < '1995-01-13';
  
  SELECT * FROM tb_cliente WHERE YEAR(DATA_NASCIMENTO) = 1995; #FUNÇÃO YEAR - FILTRA O ANO DE NASCIMENTO
  SELECT * FROM tb_cliente WHERE MONTH(DATA_NASCIMENTO) = 10; #FUNÇÃO MONTH - FILTRA O MÊS DE NASCIMENTO
  
  /*VERIFICANDO VENDEDORES QUE FORAM ADMITIDOS NA EMPRESA A PARTIR DE 2016 */
  SELECT * FROM tb_vendedores WHERE YEAR(DATA_ADMISSAO) >= 2016;
  
  /*CRIANDO CONSULTAS COM FILTROS COMPOSTOS*/ 
  SELECT * FROM tb_produto;
  SELECT * FROM tb_produto WHERE PRECO_LISTA BETWEEN 16.007 AND 16.009;
  SELECT * FROM tb_produto WHERE PRECO_LISTA >= 16.007;
  SELECT * FROM tb_produto WHERE PRECO_LISTA <= 16.009;
  SELECT * FROM tb_produto WHERE PRECO_LISTA >= 16.007 AND PRECO_LISTA <= 16.009;
  
  SELECT * FROM tb_cliente;
  SELECT * FROM tb_cliente WHERE IDADE >= 18 AND IDADE <= 22;
  SELECT * FROM tb_cliente WHERE IDADE >= 18 AND IDADE <= 22 AND SEXO = 'M';
  
  SELECT * FROM tb_cliente WHERE CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins';
  
  SELECT * FROM tb_cliente WHERE (IDADE >= 18 AND IDADE <= 22 AND SEXO = 'M') 
  OR (CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins');
  
  /*VERIFICANDO VENDEDORES QUE ESTÃO DE FÉRIAS E FORAM ADMITIDOS NA EMPRESA ANTES DE 2016 */
  SELECT * FROM tb_vendedores WHERE DE_FERIAS = 1 AND YEAR(DATA_ADMISSAO) < 2016;
  
  
  